[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Komunikator1C"
version = "0.0.1"
dependencies = [
  "flask",
  "waitress",
]
authors = [
  {name = "Michał Opar"},
  {name = "Wojciech Dudek"}
]
description = "Comunicator for class 1c"
